blank_issues_enabled: false
contact_links:
  - name: Docs or angular.devhttps://angular.io/devtools/ issue report
    url: https://github.com/angular/angular/issues/new
    about: Report an issue in Angular's documentation or angular.dev application
  - name: Security issue disclosure
    url: https://angular.dev/best-practices/security#report-issues
    about: Report a security issue in Angular Framework, Material, or CLI
  - name: Support request
    url: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#question
    about: Questions and requests for support.
  - name: Angular Framework
    url: https://github.com/angular/angular/issues/new/choose
    about: Issues and feature requests for Angular Framework
  - name: Angular Material
    url: https://github.com/angular/components/issues/new/choose
    about: Issues and feature requests for Angular Material
